# _config.yml

title: Data Analytics Portfolio
description: Showcasing my data analytics projects using Excel, Power BI, SQL, and Tableau.
theme:  minimal-mistakes-jekyll 

# Additional customizations
show_downloads: true
show_excerpts: true
